package smartexchange.expert.util;

import java.util.HashMap;
import java.util.Map;

import smartexchange.expert.R;

public class Constants {

    public static final String ANOTHER_DATE_FORMAT = "yyyy-MM-dd";
    public static final String DATE_FORMAT = "dd-MM-yyyy";
    public static final String DATE_FORMAT_V2 = "dd-MMM-yyyy";
    public static final String DATE_FORMAT_V3 = "dd-MMMM-yyyy";
    public static final String DATE_FORMAT_V4 = "yyyy-MMM-dd";
    public static final String DATE_FORMAT_V5 = "yyyy-MMMM-dd";
    public static final String DATETIME_FORMAT = "dd-MM-yyyy HH:mm:ss";
    public static final String CALCULATOR = "calculator";
    public static final String CONVERTER = "convertor";
    public static final String INTENT_TYPE = "intent_type";
    public static final String FIRST_TIME = "fto";
    public static final String LANGUAGE = "language";
    public static final String AUTO_UPDATE = "auto_update";
    public static final String NOTIFICATION = "notification";
    public static final String PREFERED_DATE_FORMAT = "prefered_date_format";
    public static final int CHANGE_LANGUAGE_REQUEST_CODE = 222;
    public static final int CHANGE_LANGUAGE_RESULT_CODE = 223;
    public static final int CHANGE_DATE_FORMAT_REQUEST_CODE = 332;
    public static final int CHANGE_DATE_FORMAT_RESULT_CODE = 333;
    public static final int SPLASH_SCREEN_DURATION = 900;
    public static final int REGION_CALCULATOR_REQUEST_CODE = 94;
    public static final int REGION_CALCULATOR_RESULT_CODE = 49;
    public static final int REGION_CHOOSE_REQUEST_CODE = 112;
    public static final int REGION_CHOOSE_RESULT_CODE = 113;
    public static final String REGION = "region";
    public static final String DATE_PREF = "date_pref";
    public static final String date_key = "date_key";
    public static final String BNR_URL = "http://www.bnr.ro/nbrfxrates.xml";
    public static final Map<String , Integer> EXCHANGE_MAP = new HashMap<String , Integer>() {{
        put(RON,    R.drawable.ic_flag_of_romania);
        put(AED, R.drawable.ic_flag_of_the_united_arab_emirates);
        put(AUD,   R.drawable.australia);
        put(BGN,    R.drawable.ic_flag_of_bulgaria);
        put(BRL, R.drawable.brazil);
        put(CAD,   R.drawable.ic_flag_of_canada);
        put(CHF,    R.drawable.ic_flag_of_switzerland);
        put(CNY, R.drawable.ic_flag_of_the_peoples_republic_of_china);
        put(CZK,   R.drawable.ic_flag_of_the_czech_republic);
        put(DKK,    R.drawable.ic_flag_of_denmark);
        put(EGP, R.drawable.ic_flag_of_egypt);
        put(EUR,   R.drawable.europe);
        put(GBP,    R.drawable.ic_flag_of_the_united_kingdom);
        put(HRK, R.drawable.ic_flag_of_croatia);
        put(HUF,   R.drawable.ic_flag_of_hungary);
        put(INR,    R.drawable.ic_flag_of_india);
        put(JPY, R.drawable.ic_flag_of_japan);
        put(KRW,   R.drawable.southkorea);
        put(MDL,    R.drawable.ic_flag_of_moldova);
        put(MXN, R.drawable.ic_flag_of_mexico);
        put(NOK,   R.drawable.ic_flag_of_norway);
        put(NZD,    R.drawable.newzealand);
        put(PLN, R.drawable.ic_flag_of_poland);
        put(RSD,   R.drawable.serbia);
        put(RUB,    R.drawable.ic_flag_of_russia);
        put(SEK, R.drawable.ic_flag_of_sweden);
        put(THB,   R.drawable.ic_flag_of_thailand);
        put(TRY,    R.drawable.ic_flag_of_turkey);
        put(UAH, R.drawable.ic_flag_of_ukraine);
        put(USD,   R.drawable.us);
        put(XAU,    R.drawable.ic_flag_of_romania);
        put(XDR, R.drawable.ic_flag_of_romania);
        put(ZAR,   R.drawable.ic_flag_of_south_africa);
    }};
    public static final String RON = "RON";
    public static final String AED = "AED";
    public static final String AUD = "AUD";
    public static final String BGN = "BGN";
    public static final String BRL = "BRL";
    public static final String CAD = "CAD";
    public static final String CHF = "CHF";
    public static final String CNY = "CNY";
    public static final String CZK = "CZK";
    public static final String DKK = "DKK";
    public static final String EGP = "EGP";
    public static final String EUR = "EUR";
    public static final String GBP = "GBP";
    public static final String HRK = "HRK";
    public static final String HUF = "HUF";
    public static final String INR = "INR";
    public static final String JPY = "JPY";
    public static final String KRW = "KRW";
    public static final String MDL = "MDL";
    public static final String MXN = "MXN";
    public static final String NOK = "NOK";
    public static final String NZD = "NZD";
    public static final String PLN = "PLN";
    public static final String RSD = "RSD";
    public static final String RUB = "RUB";
    public static final String SEK = "SEK";
    public static final String THB = "THB";
    public static final String TRY = "TRY";
    public static final String UAH = "UAH";
    public static final String USD = "USD";
    public static final String XAU = "XAU";
    public static final String XDR = "XDR";
    public static final String ZAR = "ZAR";

}
